/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SociosRouteImport } from './routes/socios'
import { Route as OrcamentoRouteImport } from './routes/orcamento'
import { Route as ObraRouteImport } from './routes/obra'
import { Route as MinhaPosicaoRouteImport } from './routes/minha-posicao'
import { Route as LancamentosRouteImport } from './routes/lancamentos'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const SociosRoute = SociosRouteImport.update({
  id: '/socios',
  path: '/socios',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentoRoute = OrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => rootRouteImport,
} as any)
const ObraRoute = ObraRouteImport.update({
  id: '/obra',
  path: '/obra',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaPosicaoRoute = MinhaPosicaoRouteImport.update({
  id: '/minha-posicao',
  path: '/minha-posicao',
  getParentRoute: () => rootRouteImport,
} as any)
const LancamentosRoute = LancamentosRouteImport.update({
  id: '/lancamentos',
  path: '/lancamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/documentos': typeof DocumentosRoute
  '/lancamentos': typeof LancamentosRoute
  '/minha-posicao': typeof MinhaPosicaoRoute
  '/obra': typeof ObraRoute
  '/orcamento': typeof OrcamentoRoute
  '/socios': typeof SociosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/documentos': typeof DocumentosRoute
  '/lancamentos': typeof LancamentosRoute
  '/minha-posicao': typeof MinhaPosicaoRoute
  '/obra': typeof ObraRoute
  '/orcamento': typeof OrcamentoRoute
  '/socios': typeof SociosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/documentos': typeof DocumentosRoute
  '/lancamentos': typeof LancamentosRoute
  '/minha-posicao': typeof MinhaPosicaoRoute
  '/obra': typeof ObraRoute
  '/orcamento': typeof OrcamentoRoute
  '/socios': typeof SociosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/documentos'
    | '/lancamentos'
    | '/minha-posicao'
    | '/obra'
    | '/orcamento'
    | '/socios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/documentos'
    | '/lancamentos'
    | '/minha-posicao'
    | '/obra'
    | '/orcamento'
    | '/socios'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/documentos'
    | '/lancamentos'
    | '/minha-posicao'
    | '/obra'
    | '/orcamento'
    | '/socios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DocumentosRoute: typeof DocumentosRoute
  LancamentosRoute: typeof LancamentosRoute
  MinhaPosicaoRoute: typeof MinhaPosicaoRoute
  ObraRoute: typeof ObraRoute
  OrcamentoRoute: typeof OrcamentoRoute
  SociosRoute: typeof SociosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/socios': {
      id: '/socios'
      path: '/socios'
      fullPath: '/socios'
      preLoaderRoute: typeof SociosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamento': {
      id: '/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof OrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obra': {
      id: '/obra'
      path: '/obra'
      fullPath: '/obra'
      preLoaderRoute: typeof ObraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-posicao': {
      id: '/minha-posicao'
      path: '/minha-posicao'
      fullPath: '/minha-posicao'
      preLoaderRoute: typeof MinhaPosicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancamentos': {
      id: '/lancamentos'
      path: '/lancamentos'
      fullPath: '/lancamentos'
      preLoaderRoute: typeof LancamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DocumentosRoute: DocumentosRoute,
  LancamentosRoute: LancamentosRoute,
  MinhaPosicaoRoute: MinhaPosicaoRoute,
  ObraRoute: ObraRoute,
  OrcamentoRoute: OrcamentoRoute,
  SociosRoute: SociosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
